apps:
  patreon-archiver:
    command: 'bin/patreon-archiver'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
base: 'core24'
confinement: 'strict'
contact: 'https://github.com/Tatsh/patreon-archiver/issues'
description: 'Save Patreon content you have access to.'
donation: 'https://buymeacoffee.com/Tatsh'
grade: 'stable'
issues: 'https://github.com/Tatsh/patreon-archiver/issues'
license: 'MIT'
name: 'patreon-archiver'
parts:
  patreon-archiver:
    build-packages: []
    plugin: 'python'
    python-packages:
      - '.'
    source: '.'
    stage-packages: []
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
source-code: 'https://github.com/Tatsh/patreon-archiver'
summary: 'Save Patreon content you have access to.'
title: 'patreon-archiver'
version: '0.1.6'
website: 'https://tatsh.github.io/patreon-archiver/'
